/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package thi.adminclient.question;

import jakarta.xml.bind.JAXBContext;
import jakarta.xml.bind.JAXBException;
import jakarta.xml.bind.Unmarshaller;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import thi.adminclient.Main_boad;
import thi.model.question.Question;
import thi.model.question.Questions;

/**
 *
 * @author GiaLuong
 */
public class QuestionManager extends javax.swing.JFrame {
    private DefaultTableModel mode;
    private URL getURL;
    private HttpURLConnection http;
    private JAXBContext jabc;
    private Unmarshaller unmarshaller;
    private Question question;
    private Questions listQuestion;
    /**
     * Creates new form QuestionManager
     */
    public QuestionManager() {
        initComponents();
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLocation(200, 150);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_getQuestion = new javax.swing.JButton();
        btn_getListQuestion = new javax.swing.JButton();
        btn_addQuestion = new javax.swing.JButton();
        btn_editQuestion = new javax.swing.JButton();
        btn_deleteQuestion = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_getQuestion.setText("Tìm Câu Hỏi");
        btn_getQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_getQuestionActionPerformed(evt);
            }
        });

        btn_getListQuestion.setText("Thông tin các Câu Hỏi");
        btn_getListQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_getListQuestionActionPerformed(evt);
            }
        });

        btn_addQuestion.setText("Thêm Câu Hỏi");
        btn_addQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addQuestionActionPerformed(evt);
            }
        });

        btn_editQuestion.setText("Sửa thông tin Câu Hỏi");
        btn_editQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editQuestionActionPerformed(evt);
            }
        });

        btn_deleteQuestion.setText("Xóa Câu Hỏi");
        btn_deleteQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteQuestionActionPerformed(evt);
            }
        });

        btn_back.setText("Quay lại");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn_getQuestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_getListQuestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_addQuestion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_editQuestion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_deleteQuestion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_back, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(btn_getListQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_getQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_addQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_editQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_deleteQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        mode = new DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Môn", "Mã Câu Hỏi", "Câu Hỏi", "A","B","C","D"
            });
            jTable1.setModel(
                mode
            );
            jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            jTable1.setRowHeight(20);
            jScrollPane1.setViewportView(jTable1);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 813, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(33, 33, 33))
                .addComponent(jScrollPane1)
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void btn_getQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_getQuestionActionPerformed

        String id_subject=JOptionPane.showInputDialog(null, "Nhập mã môn học");
        String id_question=JOptionPane.showInputDialog(null, "Nhập mã câu hỏi");
        if(id_subject.length()>0)
        {
            try {
                getURL = new URL("http://localhost:8989/thitracnghiem/api/admin/question/info?id_subject="+id_subject+"&id_question="+id_question);
                http = (HttpURLConnection)getURL.openConnection();
                http.setRequestMethod("GET");
                jabc = JAXBContext.newInstance(Question.class);
                unmarshaller = jabc.createUnmarshaller();
                question = (Question)unmarshaller.unmarshal(http.getInputStream());
                mode.getDataVector().removeAllElements();
                mode.addRow(new Object[]{question.getId_subject(),question.getId_question(),question.getQuestion(),question.getAnswer_a(),question.getAnswer_b(),question.getAnswer_c(),question.getAnswer_d()});

            } catch (MalformedURLException ex) {
                Logger.getLogger(QuestionManager.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(QuestionManager.class.getName()).log(Level.SEVERE, null, ex);
            } catch (JAXBException ex) {
                Logger.getLogger(QuestionManager.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_btn_getQuestionActionPerformed

    private void btn_getListQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_getListQuestionActionPerformed
        // TODO add your handling code here:

        try {
            // TODO add your handling code here:
            getURL = new URL("http://localhost:8989/thitracnghiem/api/admin/question");
            http = (HttpURLConnection)getURL.openConnection();
            http.setRequestMethod("GET");
            
            jabc = JAXBContext.newInstance(Questions.class);
            unmarshaller = jabc.createUnmarshaller();
            
            listQuestion = (Questions)unmarshaller.unmarshal(http.getInputStream());
            mode.getDataVector().removeAllElements();
            for(Question question:listQuestion.getList())
            {
                
                mode.addRow(new Object[]{question.getId_subject(),question.getId_question(),question.getQuestion(),question.getAnswer_a(),question.getAnswer_b(),question.getAnswer_c(),question.getAnswer_d()});
            }
        } catch (MalformedURLException ex) {
            Logger.getLogger(QuestionManager.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(QuestionManager.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JAXBException ex) {
            Logger.getLogger(QuestionManager.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_getListQuestionActionPerformed

    private void btn_addQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addQuestionActionPerformed
        // TODO add your handling code here:
        new AddQuestionForm().run();
    }//GEN-LAST:event_btn_addQuestionActionPerformed

    private void btn_editQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editQuestionActionPerformed
        // TODO add your handling code here:
        new EditQuestionForm().run();
    }//GEN-LAST:event_btn_editQuestionActionPerformed

    private void btn_deleteQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteQuestionActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            String id_subject=JOptionPane.showInputDialog(null, "Nhập mã môn học");
            String id_question=JOptionPane.showInputDialog(null, "Nhập mã câu hỏi");
            if(id_question.length()>0&&id_subject.length()>0)
            {
                getURL = new URL("http://localhost:8989/thitracnghiem/api/admin/question?id_subject="+id_subject+"&id_question="+id_question);
                http = (HttpURLConnection)getURL.openConnection();
                http.setRequestMethod("DELETE");
                http.getInputStream();
            }
        } catch (MalformedURLException ex) {
            Logger.getLogger(QuestionManager.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(QuestionManager.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.btn_getListQuestionActionPerformed(evt);
    }//GEN-LAST:event_btn_deleteQuestionActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        new Main_boad().run();
        dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public void run() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuestionManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuestionManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuestionManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuestionManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuestionManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addQuestion;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_deleteQuestion;
    private javax.swing.JButton btn_editQuestion;
    private javax.swing.JButton btn_getListQuestion;
    private javax.swing.JButton btn_getQuestion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
