/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package thi.adminclient.class_manager;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jakarta.xml.bind.JAXBContext;
import jakarta.xml.bind.JAXBException;
import jakarta.xml.bind.Unmarshaller;
import java.io.IOException;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import thi.adminclient.Main_boad;
import thi.model.cl.*;
/**
 *
 * @author GiaLuong
 */
public class Class_manager extends javax.swing.JFrame {
    private DefaultTableModel mode;
    private URL getURL;
    private HttpURLConnection http;
    private JAXBContext jabc;
    private Unmarshaller unmarshaller;
    private Classes listClass;
    private thi.model.cl.Class cl;
    /**
     * Creates new form Class_manager
     */
    public Class_manager() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_getListSubjetc = new javax.swing.JButton();
        btn_getSubject = new javax.swing.JButton();
        btn_addSubject = new javax.swing.JButton();
        btn_editSubject = new javax.swing.JButton();
        btn_deleteSubject = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_getListSubjetc.setText("Thông tin các Lớp");
        btn_getListSubjetc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_getListSubjetcActionPerformed(evt);
            }
        });

        btn_getSubject.setText("Tìm Môn Lớp");
        btn_getSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_getSubjectActionPerformed(evt);
            }
        });

        btn_addSubject.setText("Thêm Môn Lớp");
        btn_addSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addSubjectActionPerformed(evt);
            }
        });

        btn_editSubject.setText("Sửa thông tin Lớp");
        btn_editSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editSubjectActionPerformed(evt);
            }
        });

        btn_deleteSubject.setText("Xóa Môn Lớp");
        btn_deleteSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteSubjectActionPerformed(evt);
            }
        });

        btn_back.setText("Quay lại");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        mode = new DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Lớp", "Mã Khoa","Tên Lớp"
            });
            jTable1.setModel(
                mode
            );
            jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            jTable1.setRowHeight(20);
            jScrollPane1.setViewportView(jTable1);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btn_getSubject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_getListSubjetc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_addSubject, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_editSubject, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_deleteSubject, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_back, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                .addGroup(layout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addComponent(btn_getListSubjetc, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(btn_getSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(btn_addSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(btn_editSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(btn_deleteSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void btn_getListSubjetcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_getListSubjetcActionPerformed
        // TODO add your handling code here:

        try {
            // TODO add your handling code here:
            getURL = new URL("http://localhost:8989/thitracnghiem/api/admin/class");
            http = (HttpURLConnection)getURL.openConnection();
            http.setRequestMethod("GET");
            jabc = JAXBContext.newInstance(Classes.class);
            unmarshaller = jabc.createUnmarshaller();
            listClass = (Classes)unmarshaller.unmarshal(http.getInputStream());
            mode.getDataVector().removeAllElements();
            for(thi.model.cl.Class cl:listClass.getList())
            {
                mode.addRow(new Object[]{cl.getId_class(),cl.getId_department(),cl.getClassname()});
            }
        } catch (MalformedURLException ex) {
            Logger.getLogger(Class_manager.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Class_manager.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JAXBException ex) {
            Logger.getLogger(Class_manager.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_getListSubjetcActionPerformed

    private void btn_getSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_getSubjectActionPerformed
        String malop=JOptionPane.showInputDialog(null, "Nhập mã lớp");
        String makhoa=JOptionPane.showInputDialog(null, "Nhập mã khoa");
        if(malop.length()>0&&makhoa.length()>0)
        {
            try {
                // TODO add your handling code here:
                getURL = new URL("http://localhost:8989/thitracnghiem/api/admin/class/info?id_class="+malop+"&id_department="+makhoa);
                http = (HttpURLConnection)getURL.openConnection();
                http.setRequestMethod("GET");
                jabc = JAXBContext.newInstance(thi.model.cl.Class.class);
                unmarshaller = jabc.createUnmarshaller();
                cl = (thi.model.cl.Class)unmarshaller.unmarshal(http.getInputStream());
                mode.getDataVector().removeAllElements();
                mode.addRow(new Object[]{cl.getId_class(),cl.getId_department(),cl.getClassname()});

            } catch (MalformedURLException ex) {
                Logger.getLogger(Class_manager.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Class_manager.class.getName()).log(Level.SEVERE, null, ex);
            } catch (JAXBException ex) {
                Logger.getLogger(Class_manager.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        else
        {
            JOptionPane.showMessageDialog(null, "nhập thiếu thông tin");
        }
    }//GEN-LAST:event_btn_getSubjectActionPerformed

    private void btn_addSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addSubjectActionPerformed
        // TODO add your handling code here:
        mode.getDataVector().removeAllElements();
        jTable1.repaint();
        new AddClassForm().run();
    }//GEN-LAST:event_btn_addSubjectActionPerformed

    private void btn_editSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editSubjectActionPerformed
        // TODO add your handling code here:
        new EditClassForm().run();
    }//GEN-LAST:event_btn_editSubjectActionPerformed

    private void btn_deleteSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteSubjectActionPerformed
        // TODO add your handling code here:
        try {
            String malop=JOptionPane.showInputDialog(null, "Nhập mã lớp");
            String makhoa=JOptionPane.showInputDialog(null, "Nhập mã khoa");
            if(malop.length()>0&&makhoa.length()>0)
            {
                getURL = new URL("http://localhost:8989/thitracnghiem/api/admin/class?id_class="+malop+"&id_department="+makhoa);
                http = (HttpURLConnection)getURL.openConnection();
                http.setRequestMethod("DELETE");
                http.getInputStream();
                this.btn_getListSubjetcActionPerformed(evt);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "nhập thiếu thông tin");
            }
        } catch (MalformedURLException ex) {
            Logger.getLogger(Class_manager.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Class_manager.class.getName()).log(Level.SEVERE, null, ex);
        } catch(Exception ex)
        {

        }

    }//GEN-LAST:event_btn_deleteSubjectActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        new Main_boad().run();
        dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public void run() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Class_manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Class_manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Class_manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Class_manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Class_manager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addSubject;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_deleteSubject;
    private javax.swing.JButton btn_editSubject;
    private javax.swing.JButton btn_getListSubjetc;
    private javax.swing.JButton btn_getSubject;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
