/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package thi.adminclient;

import java.io.IOException;
import java.nio.file.Paths;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import thi.adminclient.score.ScoreManager;
import thi.adminclient.subject.SubjectManager;
import thi.adminclient.question.QuestionManager;
import thi.adminclient.class_manager.Class_manager;
import thi.adminclient.department.Departmenet_manager;
import javax.swing.JFrame;
import thi.adminclient.user.UserManager;

/**
 *
 * @author GiaLuong
 */
public class Main_boad extends javax.swing.JFrame {
    private String admin_name;
    private String cookie;
    /**
     * Creates new form Main_boad
     */
    public Main_boad() {
        initComponents();
        setLocation(400, 150);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        try {
            Scanner sc= new Scanner(Paths.get("info.info"),"UTF-8");
            String info[] = sc.nextLine().split("[@]");
            if(info.length==2)
            {
                this.admin_name=info[0];
                label_admin_name.setText("Họ Tên : "+admin_name);
                setTitle(admin_name);
                this.cookie=info[1];
            }
        } catch (IOException ex) {
            Logger.getLogger(Main_boad.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_scoreManager = new javax.swing.JButton();
        btn_userManager = new javax.swing.JButton();
        btn_questionManager = new javax.swing.JButton();
        btn_subjectManager = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        label_admin_name = new javax.swing.JLabel();
        btn_thi = new javax.swing.JButton();
        btn_departmentManager = new javax.swing.JButton();
        btn_classManager = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_scoreManager.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_scoreManager.setText("XEM ĐIỂM");
        btn_scoreManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_scoreManagerActionPerformed(evt);
            }
        });

        btn_userManager.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_userManager.setText("QUẢN LÝ THÔNG TIN SINH VIÊN");
        btn_userManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_userManagerActionPerformed(evt);
            }
        });

        btn_questionManager.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_questionManager.setText("QUẢN LÝ THÔNG TIN CÂU HỎI");
        btn_questionManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_questionManagerActionPerformed(evt);
            }
        });

        btn_subjectManager.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_subjectManager.setText("QUẢN LÝ THÔNG TIN MÔN HỌC");
        btn_subjectManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_subjectManagerActionPerformed(evt);
            }
        });

        btn_logout.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_logout.setText("ĐĂNG XUẤT");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("TRANG CHỦ");
        jLabel1.setToolTipText("");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        label_admin_name.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        label_admin_name.setText("Admin : ");

        btn_thi.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_thi.setText("THI");
        btn_thi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thiActionPerformed(evt);
            }
        });

        btn_departmentManager.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_departmentManager.setText("QUẢN LÝ THÔNG TIN KHOA");
        btn_departmentManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_departmentManagerActionPerformed(evt);
            }
        });

        btn_classManager.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_classManager.setText("QUẢN LÝ THÔNG TIN LỚP");
        btn_classManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_classManagerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_admin_name, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_thi, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(144, 144, 144))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btn_userManager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_subjectManager, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn_classManager, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_questionManager, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_departmentManager, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(73, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btn_logout)
                                    .addComponent(btn_scoreManager, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(250, 250, 250))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_thi, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_admin_name, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_userManager, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_subjectManager, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_departmentManager, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_classManager, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_scoreManager, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btn_questionManager, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:
        new AdminClient_login().run();
        dispose();
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_userManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_userManagerActionPerformed
        // TODO add your handling code here:
        new UserManager().run();
        dispose();
    }//GEN-LAST:event_btn_userManagerActionPerformed

    private void btn_subjectManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_subjectManagerActionPerformed
        // TODO add your handling code here:
        new SubjectManager().run();
        dispose();
    }//GEN-LAST:event_btn_subjectManagerActionPerformed

    private void btn_questionManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_questionManagerActionPerformed
        // TODO add your handling code here:
        new QuestionManager().run();
        dispose();
    }//GEN-LAST:event_btn_questionManagerActionPerformed

    private void btn_scoreManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_scoreManagerActionPerformed
        // TODO add your handling code here:
        new ScoreManager().run();
        dispose();
    }//GEN-LAST:event_btn_scoreManagerActionPerformed

    private void btn_thiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thiActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn_thiActionPerformed

    private void btn_departmentManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_departmentManagerActionPerformed
        // TODO add your handling code here:
        new Departmenet_manager().run();
        dispose();
    }//GEN-LAST:event_btn_departmentManagerActionPerformed

    private void btn_classManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_classManagerActionPerformed
        // TODO add your handling code here:
        new Class_manager().run();
        dispose();
    }//GEN-LAST:event_btn_classManagerActionPerformed

    /**
     * @param args the command line arguments
     */
    public void run() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_boad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_classManager;
    private javax.swing.JButton btn_departmentManager;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_questionManager;
    private javax.swing.JButton btn_scoreManager;
    private javax.swing.JButton btn_subjectManager;
    private javax.swing.JButton btn_thi;
    private javax.swing.JButton btn_userManager;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel label_admin_name;
    // End of variables declaration//GEN-END:variables
}
