/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package thi.adminclient.subject;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jakarta.xml.bind.JAXBContext;
import jakarta.xml.bind.JAXBException;
import jakarta.xml.bind.Unmarshaller;
import java.io.IOException;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import thi.adminclient.Main_boad;
import thi.model.subject.*;

/**
 *
 * @author GiaLuong
 */
public class SubjectManager extends javax.swing.JFrame {
    private DefaultTableModel mode;
    private URL getURL;
    private HttpURLConnection http;
    private JAXBContext jabc;
    private Unmarshaller unmarshaller;
    private Subjects listSubject;
    private Subject subject;
    /**
     * Creates new form SubjectManager
     */
    public SubjectManager() {
        initComponents();
        setLocation(400, 150);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_getListSubjetc = new javax.swing.JButton();
        btn_getSubject = new javax.swing.JButton();
        btn_addSubject = new javax.swing.JButton();
        btn_editSubject = new javax.swing.JButton();
        btn_deleteSubject = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        mode = new DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Môn Học", "Tên Môn Học"
            });
            jTable1.setModel(
                mode
            );
            jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            jTable1.setRowHeight(20);
            jScrollPane1.setViewportView(jTable1);

            btn_getListSubjetc.setText("Thông tin các Môn Học");
            btn_getListSubjetc.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btn_getListSubjetcActionPerformed(evt);
                }
            });

            btn_getSubject.setText("Tìm Môn Học");
            btn_getSubject.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btn_getSubjectActionPerformed(evt);
                }
            });

            btn_addSubject.setText("Thêm Môn Học");
            btn_addSubject.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btn_addSubjectActionPerformed(evt);
                }
            });

            btn_editSubject.setText("Sửa thông tin Môn Học");
            btn_editSubject.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btn_editSubjectActionPerformed(evt);
                }
            });

            btn_deleteSubject.setText("Xóa Môn Học");
            btn_deleteSubject.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btn_deleteSubjectActionPerformed(evt);
                }
            });

            btn_back.setText("Quay lại");
            btn_back.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btn_backActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btn_getSubject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_getListSubjetc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_addSubject, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_editSubject, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_deleteSubject, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_back, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGroup(layout.createSequentialGroup()
                    .addGap(19, 19, 19)
                    .addComponent(btn_getListSubjetc, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(btn_getSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(btn_addSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(btn_editSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(btn_deleteSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(19, Short.MAX_VALUE))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void btn_getListSubjetcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_getListSubjetcActionPerformed
        // TODO add your handling code here:

        try {
            // TODO add your handling code here:
            getURL = new URL("http://localhost:8989/thitracnghiem/api/admin/subject");
            http = (HttpURLConnection)getURL.openConnection();
            http.setRequestMethod("GET");
            jabc = JAXBContext.newInstance(Subjects.class);
            unmarshaller = jabc.createUnmarshaller();
            listSubject = (Subjects)unmarshaller.unmarshal(http.getInputStream());
            mode.getDataVector().removeAllElements();
            for(Subject subject:listSubject.getList())
            {
                mode.addRow(new Object[]{subject.getId_subject(),subject.getName_subject()});
            }
        } catch (MalformedURLException ex) {
            Logger.getLogger(SubjectManager.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(SubjectManager.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JAXBException ex) {
            Logger.getLogger(SubjectManager.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_getListSubjetcActionPerformed

    private void btn_getSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_getSubjectActionPerformed
        String mamh=JOptionPane.showInputDialog(null, "Nhập mã môn học");
        if(mamh.length()>0)
        {
            try {
                // TODO add your handling code here:
                getURL = new URL("http://localhost:8989/thitracnghiem/api/admin/subject/info?id_subject="+mamh);
                http = (HttpURLConnection)getURL.openConnection();
                http.setRequestMethod("GET");
                jabc = JAXBContext.newInstance(Subject.class);
                unmarshaller = jabc.createUnmarshaller();
                subject = (Subject)unmarshaller.unmarshal(http.getInputStream());
                mode.getDataVector().removeAllElements();
                mode.addRow(new Object[]{subject.getId_subject(),subject.getName_subject()});

            } catch (MalformedURLException ex) {
                Logger.getLogger(SubjectManager.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(SubjectManager.class.getName()).log(Level.SEVERE, null, ex);
            } catch (JAXBException ex) {
                Logger.getLogger(SubjectManager.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_btn_getSubjectActionPerformed

    private void btn_addSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addSubjectActionPerformed
        // TODO add your handling code here:
        new AddSubjectForm().run();
    }//GEN-LAST:event_btn_addSubjectActionPerformed

    private void btn_editSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editSubjectActionPerformed
        // TODO add your handling code here:
        new EditSubjectForm().run();
    }//GEN-LAST:event_btn_editSubjectActionPerformed

    private void btn_deleteSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteSubjectActionPerformed
        // TODO add your handling code here:
        try {
            String mamh=JOptionPane.showInputDialog(null, "Nhập mã môn học");
            if(mamh.length()>0)
            {
                getURL = new URL("http://localhost:8989/thitracnghiem/api/admin/subject?id_subject="+mamh);
                http = (HttpURLConnection)getURL.openConnection();
                http.setRequestMethod("DELETE");
                http.getInputStream();
                this.btn_getListSubjetcActionPerformed(evt);
            }
        } catch (MalformedURLException ex) {
            Logger.getLogger(SubjectManager.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(SubjectManager.class.getName()).log(Level.SEVERE, null, ex);
        } catch(Exception ex)
        {
            
        }
        
        
    }//GEN-LAST:event_btn_deleteSubjectActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        new Main_boad().run();
        dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public void run() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubjectManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubjectManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubjectManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubjectManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SubjectManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addSubject;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_deleteSubject;
    private javax.swing.JButton btn_editSubject;
    private javax.swing.JButton btn_getListSubjetc;
    private javax.swing.JButton btn_getSubject;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
