/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package thi.adminclient.score;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jakarta.xml.bind.JAXBContext;
import jakarta.xml.bind.JAXBException;
import jakarta.xml.bind.Unmarshaller;
import java.io.IOException;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import thi.adminclient.Main_boad;
import thi.model.score.*;

/**
 *
 * @author GiaLuong
 */
public class ScoreManager extends javax.swing.JFrame {
    private DefaultTableModel mode;
    private URL getURL;
    private HttpURLConnection http;
    private JAXBContext jabc;
    private Unmarshaller unmarshaller;
    private Scores listScore;
    private Score score;
    /**
     * Creates new form ScoreManager
     */
    public ScoreManager() {
        initComponents();
        setLocation(400, 150);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_fliter_by_id_subject = new javax.swing.JButton();
        btn_getListSubjetc1 = new javax.swing.JButton();
        btn_fliter_by_id_user = new javax.swing.JButton();
        btn_fliter = new javax.swing.JButton();
        btn_fliter1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        mode = new DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Môn Học", "Mã Sinh Viên","Điểm"
            });
            jTable1.setModel(
                mode
            );
            jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            jTable1.setRowHeight(20);
            jScrollPane1.setViewportView(jTable1);

            btn_fliter_by_id_subject.setText("Lọc theo môn học");
            btn_fliter_by_id_subject.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btn_fliter_by_id_subjectActionPerformed(evt);
                }
            });

            btn_getListSubjetc1.setText("Thông tin Điểm");
            btn_getListSubjetc1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btn_getListSubjetc1ActionPerformed(evt);
                }
            });

            btn_fliter_by_id_user.setText("Lọc theo sinh viên");
            btn_fliter_by_id_user.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btn_fliter_by_id_userActionPerformed(evt);
                }
            });

            btn_fliter.setText("Tìm điểm");
            btn_fliter.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btn_fliterActionPerformed(evt);
                }
            });

            btn_fliter1.setText("Quay lại");
            btn_fliter1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btn_fliter1ActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(42, 42, 42)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btn_fliter_by_id_subject, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                        .addComponent(btn_getListSubjetc1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_fliter_by_id_user, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                        .addComponent(btn_fliter, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                        .addComponent(btn_fliter1, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                    .addGap(44, 44, 44)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                .addGroup(layout.createSequentialGroup()
                    .addGap(36, 36, 36)
                    .addComponent(btn_getListSubjetc1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(btn_fliter_by_id_subject, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(btn_fliter_by_id_user, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(btn_fliter, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(btn_fliter1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void btn_fliter_by_id_subjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fliter_by_id_subjectActionPerformed
        // TODO add your handling code here:

        try {
            String mamh = JOptionPane.showInputDialog("Mã môn học");
            if(mamh.length()>0)
            {
                getURL = new URL("http://localhost:8989/thitracnghiem/api/admin/score");
                http = (HttpURLConnection)getURL.openConnection();
                http.setRequestMethod("GET");
                jabc = JAXBContext.newInstance(Scores.class);
                unmarshaller = jabc.createUnmarshaller();
                listScore = (Scores)unmarshaller.unmarshal(http.getInputStream());
                mode.getDataVector().removeAllElements();
                jTable1.repaint();
                for(Score score:listScore.getList())
                {
                    
                    if(score.getId_subject().compareTo(mamh)==0)mode.addRow(new Object[]{score.getId_subject(),score.getId_user(),score.getScore()});
                }
            }
            
        } catch (MalformedURLException ex) {
            Logger.getLogger(ScoreManager.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ScoreManager.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JAXBException ex) {
            Logger.getLogger(ScoreManager.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_fliter_by_id_subjectActionPerformed

    private void btn_getListSubjetc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_getListSubjetc1ActionPerformed
        // TODO add your handling code here:
        try {

                getURL = new URL("http://localhost:8989/thitracnghiem/api/admin/score");
                http = (HttpURLConnection)getURL.openConnection();
                http.setRequestMethod("GET");
                jabc = JAXBContext.newInstance(Scores.class);
                unmarshaller = jabc.createUnmarshaller();
                listScore = (Scores)unmarshaller.unmarshal(http.getInputStream());
                mode.getDataVector().removeAllElements();
                for(Score score:listScore.getList())
                {
                    mode.addRow(new Object[]{score.getId_subject(),score.getId_user(),score.getScore()});
                }
            
        } catch (MalformedURLException ex) {
            Logger.getLogger(ScoreManager.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ScoreManager.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JAXBException ex) {
            Logger.getLogger(ScoreManager.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_getListSubjetc1ActionPerformed

    private void btn_fliter_by_id_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fliter_by_id_userActionPerformed
        // TODO add your handling code here:
        try {
            String masv = JOptionPane.showInputDialog("Mã sinh viên");
            if(masv.length()>0)
            {
                getURL = new URL("http://localhost:8989/thitracnghiem/api/admin/score");
                http = (HttpURLConnection)getURL.openConnection();
                http.setRequestMethod("GET");
                jabc = JAXBContext.newInstance(Scores.class);
                unmarshaller = jabc.createUnmarshaller();
                listScore = (Scores)unmarshaller.unmarshal(http.getInputStream());
                mode.getDataVector().removeAllElements();
                jTable1.repaint();
                for(Score score:listScore.getList())
                {
                    
                    if(score.getId_user().compareTo(masv)==0)mode.addRow(new Object[]{score.getId_subject(),score.getId_user(),score.getScore()});
                }
            }
            
        } catch (MalformedURLException ex) {
            Logger.getLogger(ScoreManager.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ScoreManager.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JAXBException ex) {
            Logger.getLogger(ScoreManager.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_fliter_by_id_userActionPerformed

    private void btn_fliterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fliterActionPerformed
        // TODO add your handling code here:
        try {
            String mamh = JOptionPane.showInputDialog("Mã môn học");
            String masv = JOptionPane.showInputDialog("Mã sinh viên");
            if(masv.length()>0&&mamh.length()>0)
            {
                getURL = new URL("http://localhost:8989/thitracnghiem/api/admin/score/info?id_subject="+mamh+"&id_user="+masv);
                http = (HttpURLConnection)getURL.openConnection();
                http.setRequestMethod("GET");
                jabc = JAXBContext.newInstance(Score.class);
                unmarshaller = jabc.createUnmarshaller();
                score = (Score)unmarshaller.unmarshal(http.getInputStream());
                mode.getDataVector().removeAllElements();
                mode.addRow(new Object[]{score.getId_subject(),score.getId_user(),score.getScore()});
            }
            
        } catch (MalformedURLException ex) {
            Logger.getLogger(ScoreManager.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ScoreManager.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JAXBException ex) {
            Logger.getLogger(ScoreManager.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_fliterActionPerformed

    private void btn_fliter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fliter1ActionPerformed
        // TODO add your handling code here:
        new Main_boad().run();
        dispose();
    }//GEN-LAST:event_btn_fliter1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void run() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScoreManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScoreManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScoreManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScoreManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScoreManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_fliter;
    private javax.swing.JButton btn_fliter1;
    private javax.swing.JButton btn_fliter_by_id_subject;
    private javax.swing.JButton btn_fliter_by_id_user;
    private javax.swing.JButton btn_getListSubjetc1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
